Bump to support go 1.10
Failed to build because sql driver.Connector only supported after go 1.10.

```
lib/pq/notify.go:47:2: undefined: driver.Connector
```